# FastWeb 数据模块配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:fastweb}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP 连接池配置
    hikari:
      # 连接池名称
      pool-name: FastWebHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 连接超时时间(毫秒)
      connection-timeout: 30000
      # 空闲连接超时时间(毫秒)
      idle-timeout: 600000
      # 连接最大生命周期(毫秒)
      max-lifetime: 1800000
      # 连接验证查询
      validation-query: SELECT 1
      # 是否在连接前验证
      validation-timeout: 5000
      # 连接泄漏检测(毫秒)
      leak-detection-threshold: 60000

# MyBatis-Plus 配置
mybatis-plus:
  # 全局配置
  global-config:
    db-config:
      # 主键类型
      id-type: auto
      # 逻辑删除字段名
      logic-delete-field: is_deleted
      # 逻辑已删除值
      logic-delete-value: null
      # 逻辑未删除值
      logic-not-delete-value: 0
      # 字段验证策略
      field-strategy: not_null
      # 驼峰下划线转换
      table-underline: true
      # 大写命名
      capital-mode: false
      # 刷新mapper
      refresh-mapper: false
  # 配置
  configuration:
    # 驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 缓存配置
    cache-enabled: false
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 全局启用或禁用延迟加载
    lazy-loading-enabled: true
    # 积极延迟加载
    aggressive-lazy-loading: false
    # 是否允许单一语句返回多结果集
    multiple-result-sets-enabled: true
    # 使用列标签代替列名
    use-column-label: true
    # 允许JDBC支持自动生成主键
    use-generated-keys: true
    # 自动映射行为
    auto-mapping-behavior: partial
    # 自动映射未知列
    auto-mapping-unknown-column-behavior: none
    # 默认枚举处理类型
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  # Mapper XML文件位置
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  # 类型别名包
  type-aliases-package: com.company.fastweb.**.model.po
  # 类型枚举包
  type-enums-package: com.company.fastweb.**.enums

# FastWeb 数据模块配置
fastweb:
  # 多租户配置
  tenant:
    # 是否启用多租户
    enabled: true
    # 租户字段名
    column: tenant_id
    # 忽略多租户的表
    ignore-tables:
      - t_sys_config
      - t_sys_dict
      - t_sys_dict_data
      - t_sys_tenant
  
  # 分页配置
  page:
    # 默认页码
    default-page: 1
    # 默认每页条数
    default-size: 10
    # 最大每页条数
    max-size: 100
    # 是否合理化分页
    reasonable: true
    # 是否返回总记录数
    search-count: true

# 日志配置
logging:
  level:
    # MyBatis-Plus SQL日志
    com.baomidou.mybatisplus: debug
    # 数据层日志
    com.company.fastweb.core.data: debug
    # Mapper接口日志
    com.company.fastweb.**.mapper: debug