fastweb:
  cache:
    enabled: true
    # 缓存配置集合，可以定义多个缓存区域
    configs:
      # 默认缓存配置，当找不到特定名称的缓存时使用
      default:
        name: "default"
        expireTime: 3600 # 过期时间（秒），这里是1小时
        local:
          enabled: true
          initialCapacity: 100 # 本地缓存初始容量
          maximumSize: 500   # 本地缓存最大容量
        redis:
          enabled: true

      # 用户信息缓存
      user:
        name: "user"
        expireTime: 1800 # 30分钟
        local:
          enabled: true
          initialCapacity: 50
          maximumSize: 200
        redis:
          enabled: true

      # 数据字典缓存
      dict:
        name: "dict"
        expireTime: 86400 # 24小时
        local:
          enabled: true
          initialCapacity: 100
          maximumSize: 1000
        redis:
          enabled: true

# Spring Redis 基础配置 (供 RedisTemplate 和 RedisCacheManager 使用)
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Redisson 分布式锁配置 (由 redisson-spring-boot-starter 自动加载)
  redisson:
    # Redisson 配置文件路径，如果使用下面的配置，则无需指定 file
    # file: classpath:redisson.yaml 
    single-server-config:
      address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
      password: ${spring.data.redis.password}
      database: ${spring.data.redis.database}
      client-name: "fastweb-cache"
      connection-pool-size: 64
      connection-minimum-idle-size: 10
      subscription-connection-pool-size: 50
      connect-timeout: 10000
      timeout: 3000