# Redis缓存配置
spring:
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器端口
    port: 6379
    # Redis服务器密码
    password: 
    # 使用的数据库索引
    database: 0
    # 连接超时时间（毫秒）
    timeout: 3000
    # 连接超时时间（毫秒）
    connect-timeout: 3000
    # 连接池配置
    pool:
      # 最大连接数
      max-active: 8
      # 最大空闲连接数
      max-idle: 8
      # 最小空闲连接数
      min-idle: 0
      # 连接空闲时间（毫秒）
      idle-timeout: 60000
    
    # Redisson配置
    redisson:
      # 是否启用Redisson
      enabled: true
      # 单节点配置
      single-server-config:
        # 连接地址
        address: "redis://localhost:6379"
        # 数据库索引
        database: 0
        # 连接池大小
        connection-pool-size: 64
        # 最小空闲连接数
        connection-minimum-idle-size: 10
        # 连接空闲超时时间
        idle-connection-timeout: 10000
        # 连接超时时间
        connect-timeout: 10000
        # 响应超时时间
        timeout: 3000

# 缓存配置
fastweb:
  cache:
    # 默认缓存过期时间（分钟）
    default-ttl: 30
    # 用户缓存过期时间（分钟）
    user-ttl: 30
    # 字典缓存过期时间（小时）
    dict-ttl: 1
    # 配置缓存过期时间（小时）
    config-ttl: 2
    # 是否启用缓存
    enabled: true
    # 是否启用缓存统计
    statistics-enabled: true

# 日志配置
logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG